bolsa_trabajo/urls.py
from django.urls import path

from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from bolsa_trabajo import views

app_name='bolsa_trabajo'

urlpatterns = [
    path('', views.bt_main, name="bt-home"),
    path('empresa_add/', views.empresa_add, name="empresa-add"),
    path('<str:id>/empresa_delete', views.empresa_delete, name="empresa-delete"),
    path('<str:id>/empresa_edit', views.empresa_edit, name="empresa-edit"),
    path('<str:id>', views.empresa_detail, name="empresa-detail"),
    path('<str:id>/contacto_add', views.empresa_contacto_add, name="contacto-add"),
    path('contacto_delete/<str:id>/', views.empresa_contacto_delete, name="contacto-delete")

]




urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

exaven/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

app_name='exaven'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.homepage, name="home"),
    path('edu_continua/', views.edu_continua, name="edu-continua"),
    path('titulacion/', views.titulacion, name="titulacion"),
    path('accounts/', include('accounts.urls')),
    path('bolsa_trabajo/', include('bolsa_trabajo.urls', namespace='bolsa_trabajo')),
    path('encuesta/', include('encuesta.urls'))
]




urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bolsa_trabajo/models.py
import os
from django.db import models

# Create your models here.


class Empresa(models.Model):
    nombre = models.CharField(max_length=30, blank=False)
    telefono = models.CharField(max_length=20, blank=True, null=True)
    codigo_postal = models.PositiveIntegerField(blank=True, null=True)
    calle = models.CharField(max_length=20, blank=True, null=True)
    colonia = models.CharField(max_length=20, blank=True, null=True)
    numero = models.SmallIntegerField(blank=True, null=True)
    ciudad = models.CharField(max_length=15, blank=True, null=True)
    estado = models.CharField(max_length=15, blank=True, null=True)
    pais = models.CharField(max_length=15, blank=True, null=True)

class Contacto_Empresa(models.Model):
    empresa = models.ForeignKey(Empresa, default=None, on_delete=models.CASCADE)
    nombre = models.CharField(max_length=30, blank=False)
    telefono = models.CharField(max_length=20, blank=True, null=True)
    email = models.EmailField(blank=True, null=True)

bolsa_trabajo/forms.py
from django import forms
from bolsa_trabajo import models

class AddEmpresaForm(forms.ModelForm):
    required_css_class = 'required'
    def clean(self):
        telefono = self.cleaned_data.get('telefono')
    
    class Meta:
        model = models.Empresa
        fields = [ 'nombre', 'telefono', 'codigo_postal', 'calle', 'colonia', 'numero', 'ciudad', 'estado', 'pais' ]
        labels = {
            'nombre': 'Nombre',
            'telefono': 'Teléfono',
            'codigo_postal': 'Código Postal',
            'calle': 'Calle',
            'colonia': 'Colonia',
            'numero': 'Número',
            'ciudad': 'Ciudad',
            'estado': 'Estado',
            'pais': 'País'
        }

class AddContactoForm(forms.ModelForm):
    required_css_class = 'required'
    def clean(self):
        email = self.cleaned_data.get('email')
        telefono = self.cleaned_data.get('telefono')

        if not email and not telefono:
            msg = forms.ValidationError("Especificar telefono o correo electronico")
            self.add_error('email', msg)
            self.add_error('telefono', msg)
            raise msg
    
    class Meta:
        model = models.Contacto_Empresa
        fields = [ 'empresa', 'nombre', 'telefono', 'email']

bolsa_trabajo/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from django.core.exceptions import ValidationError
from django.contrib import messages
from .models import Empresa, Contacto_Empresa
from bolsa_trabajo import forms

# Create your views here.


def bt_main(request):
    empresas = Empresa.objects.all().order_by('-nombre')
    contacto = Contacto_Empresa.objects.all().order_by('-id').first()

    return render(request, 'bt_home.html', {'empresas':empresas, 'contacto':contacto})

def empresa_detail(request, id):
    
    empresa = Empresa.objects.get(id=id)
    empresa = get_object_or_404(Empresa, id=id)
    
    contactos = Contacto_Empresa.objects.all().filter(empresa_id=id).order_by("-id")
    

    return render(request, 'empresa_detail.html', {'empresa':empresa, 'contactos':contactos})

def empresa_add(request):
    if request.method == 'POST':
        form = forms.AddEmpresaForm(request.POST)
        if form.is_valid():
            #guardar empresa a la base de datos
            instance = form.save(commit=False)
            instance.save()
            messages.success(request, 'Empresa Registrada Correctamente')
            return redirect('bolsa_trabajo:bt-home')
        else:
            messages.warning(request, 'Error al Registrar Empresa')
            return redirect('bolsa_trabajo:bt-home')
    else:
        form = forms.AddEmpresaForm()

    return render(request, 'bt_home.html', {'form': form})

   

def empresa_edit(request, id):
    empresa = Empresa.objects.get(id=id)
    if request.method == 'POST':
        form = forms.AddEmpresaForm(request.POST or None, instance=empresa)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.save()
            messages.success(request, 'Informacion Actualizada')
            return redirect('bolsa_trabajo:empresa-detail', empresa.id)

        else:
            messages.warning(request, 'Error al Actualizar')
            return redirect('bolsa_trabajo:empresa-detail', empresa.id)
    else:
        form = forms.AddEmpresaForm(instance=empresa)
    
    return render(request, 'empresa_detail.html', {'empresa':empresa, 'form':form})

def empresa_delete(request,id):
    contactos = Contacto_Empresa.objects.all().filter(empresa_id=id)
    empresa = Empresa.objects.get(id=id)
    contactos.delete()
    empresa.delete()
    messages.info(request,'Empresa eliminada')
    return redirect('bolsa_trabajo:bt-home')
    

def empresa_contacto_add(request, id):
    empresa = Empresa.objects.get(id=id)
    if request.method == 'POST':
        form = forms.AddContactoForm(request.POST)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.save()
            messages.success(request, 'Contacto registrado correctamente')
        
            return redirect('bolsa_trabajo:empresa-detail', empresa.id)
        else:
            messages.warning(request, 'Error al Registrar Contacto')
            return redirect('bolsa_trabajo:empresa-detail', empresa.id)
    return redirect('bolsa_trabajo:empresa-detail', empresa.id)

def empresa_contacto_edit(request):
    
    return HttpResponse('contactoEdit')

def empresa_contacto_delete(request, id):
    
    contacto = Contacto_Empresa.objects.get(id=id)
    empresa = Empresa.objects.get(id=contacto.empresa_id)
    contacto.delete()
    messages.info(request, 'Contacto Eliminado')

    return redirect('bolsa_trabajo:empresa-detail', empresa.id)

bolsa_trabajo/templates/add_contacto_empresa_modal.html
<div class="modal fade" id="add_contacto_empresa_modal" tabindex="-1" role="dialog" aria-labelledby="contactoModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="contactoModalLabel">Registrar Contacto</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
      
              <form class="site-form" action="{% url 'bolsa_trabajo:contacto-add' empresa.id %}" method="post">
                {% csrf_token %}
      
                <div class="form-group">

                <input type="hidden" name="empresa" class="form-control" id="empresa-id" value={{empresa.id}}>
                    
                <label for="nombre-contacto">Nombre</label>
                  <input type="text" name="nombre" class="form-control" id="nombre-contacto" placeholder="Nombre completo de contacto" required>
      
                  <label for="tel-contacto">Telefono</label>
                  <input type="text" name="telefono" class="form-control" id="tel-contacto" placeholder="Telefono">

                  <label for="email-contacto">Email</label>
                  <input type="text" name="email" class="form-control" id="email-contacto" placeholder="Email">

                </div>
      
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
              <button type="submit" class="btn btn-success">Guardar</button>
            </div>
      
          </form>
      
          </div>
        </div>
      </div>

bolsa_trabajo/templates/add_empresa_modal.html
<div class="modal fade" id="add_empresa_modal" tabindex="-1" role="dialog" aria-labelledby="empresaModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="empresaModalLabel">Registrar Empresa</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">


        <form class="site-form" action="{% url 'bolsa_trabajo:empresa-add' %}" method="post">
          {% csrf_token %}

          <div class="form-group">
              <label for="nombre-empresa">Nombre</label>
            <input type="text" name="nombre" class="form-control" id="nombre-empresa" placeholder="Nombre de la empresa" required>

            <label for="tel-empresa">Telefono</label>
            <input type="text" name="telefono" class="form-control" id="tel-empresa" placeholder="Telefono" required>

            <hr>

            <p>Dirección</p>

            <label for="calle-empresa">Calle</label>
            <input type="text" name="calle" class="form-control" id="calle-empresa" placeholder="Calle">


            <label for="colonia-empresa">Colonia</label>
            <input type="text" name="colonia" class="form-control" id="colonia-empresa" placeholder="Colonia">


            <label for="numero-empresa">Numero</label>
            <input type="text" name="numero" class="form-control" id="numero-empresa" placeholder="Numero">

            <label for="codigopostal-empresa">Codigo Postal</label>
            <input type="text" name="codigo_postal" class="form-control" id="codigopostal-empresa" placeholder="Codigo Postal">

            <label for="ciudad-empresa">Ciudad</label>
            <input type="text" name="ciudad" class="form-control" id="ciudad-empresa" placeholder="Ciudad">

            <label for="estado-empresa">Estado</label>
            <input type="text" name="estado" class="form-control" id="estado-empresa" placeholder="Estado">

            <label for="pais-empresa">País</label>
            <input type="text" name="pais" class="form-control" id="pais-empresa" placeholder="País">
          </div>

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
        <button type="submit" class="btn btn-success">Guardar</button>
      </div>

    </form>

    </div>
  </div>
</div>

bolsa_trabajo/templates/bt_home.html
{% extends 'base.html' %}
{% load static from staticfiles %}

{% block subtitle %}
Bolsa de Trabajo
{% endblock %}

{% block styles %}

<link rel="stylesheet" href="{% static '/styles/bolsa_trabajo_styles/styles.css' %}">
{% endblock %}

{% block content %}
<h1 class="text-center">Bolsa de Trabajo</h1>

{% if messages %}
<div class="alert alert-warning alert-dismissible fade show align-self-center" role="alert">
   <ul>
       {% for message in messages %}
       <li>{{ message }}</li>
       {% endfor %}
   </ul>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
    </button>
</div>
{% endif %}

<div class="row">
    <div class="col-lg-4 col-lg-offset-4">
        <input type="search" id="search" value="" class="form-control" placeholder="Buscar...">
    </div>
  </div>

<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#add_empresa_modal">
  Registrar Empresa
</button>
<br>
<table class="table table-hover">
    <thead>
      <tr>
        <th scope="col">Empresa</th>
        <th scope="col">Telefono</th>
        <th scope="col">Contacto</th>
        <th scope="col">Direccion</th>
      </tr>
    </thead>
    <tbody>
      {% for empresa in empresas %}
      <tr class="clickable-row" data-href="{% url 'bolsa_trabajo:empresa-detail' empresa.id %}">
          <td>{{ empresa.nombre }}</td>
          <td>{{empresa.telefono}}</td>
          <td>{{contacto.nombre}}</td>
          <td>{{empresa.calle}} {{empresa.numero}} {{empresa.colonia}}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>

{% include 'add_empresa_modal.html' %}



  
{% endblock %}

{% block scripts %}

<script src="{% static 'scripts/bolsa_trabajo_scripts/scripts.js' %}"></script>

<script src="{% static '/plugins/jquery-searchable/jquery.searchable.js' %}"></script>
<script type="text/javascript">
  $(function () {
    $( '.table' ).searchable();
  });
</script>

<script type="text/javascript">
    $(document).ready(function($) {
      $(".clickable-row").click(function() {
          window.location = $(this).data("href");
      });
  });
</script>
{% endblock %}

bolsa_trabajo/templates/delete_contacto_empresa_modal.html
<div id="delete_contacto_empresa_modal" class="modal fade" role="dialog">
        <div class="modal-dialog">
      
          <!-- Modal content-->
          <div class="modal-content">
            <div class="modal-header">
            <h4 class="modal-title">Confirmar Eliminacion</h4>
              <button type="button" class="close" data-dismiss="modal">&times;</button>
              
            </div>
            <div class="modal-body">
              <p>Desea eliminar al contacto del sistema?</p>
            </div>
            <div class="modal-footer">
                  <button type="button" class="btn btn-secondary mr-2" data-dismiss="modal">
                        Cancelar
                      </button>
      
                      <a class="btn btn-danger" href="{% url 'bolsa_trabajo:contacto-delete' contacto.id %}" role="button">Eliminar</a>
          
            </div>
          </div>
      
        </div>
      </div>

bolsa_trabajo/templates/delete_empresa_modal.html
<div id="delete_empresa_modal" class="modal fade" role="dialog">
        <div class="modal-dialog">
      
          <!-- Modal content-->
          <div class="modal-content">
            <div class="modal-header">
            <h4 class="modal-title">Confirmar Eliminacion</h4>
              <button type="button" class="close" data-dismiss="modal">&times;</button>
              
            </div>
            <div class="modal-body">
              <p>Desea eliminar a la empresa del sistema?</p>
              <p>También se eliminarán los contactos asociados a la misma.</p>
            </div>
            <div class="modal-footer">
                  <button type="button" class="btn btn-secondary mr-2" data-dismiss="modal">
                        Cancelar
                      </button>
      
                      <a class="btn btn-danger" href="{% url 'bolsa_trabajo:empresa-delete' empresa.id %}" role="button">Eliminar</a>
          
            </div>
          </div>
      
        </div>
      </div>

bolsa_trabajo/templates/edit_empresa_modal.html
<div class="modal fade" id="edit_empresa_modal" tabindex="-1" role="dialog" aria-labelledby="editempresaModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="editempresaModalLabel">Actualizar Informacion de Empresa</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
      
              <form class="site-form" action="{% url 'bolsa_trabajo:empresa-edit' empresa.id %}" method="post">
                {% csrf_token %}
      
                <div class="form-group">
                    <label for="nombre-empresa">Nombre</label>
                  <input type="text" name="nombre" class="form-control" id="nombre-empresa" placeholder="Nombre de la empresa" value="{{empresa.nombre}}" required>
      
                  <label for="tel-empresa">Telefono</label>
                  <input type="text" name="telefono" class="form-control" id="tel-empresa" placeholder="Telefono" value="{{empresa.telefono}}" required>
      
                  <hr>
      
                  <p>Dirección</p>
      
                  <label for="calle-empresa">Calle</label>
                  <input type="text" name="calle" class="form-control" id="calle-empresa" placeholder="Calle" value="{{empresa.calle}}">
      
      
                  <label for="colonia-empresa">Colonia</label>
                  <input type="text" name="colonia" class="form-control" id="colonia-empresa" placeholder="Colonia" value="{{empresa.colonia}}">
      
      
                  <label for="numero-empresa">Numero</label>
                  <input type="text" name="numero" class="form-control" id="numero-empresa" placeholder="Numero" value="{{empresa.numero}}">
      
                  <label for="codigopostal-empresa">Codigo Postal</label>
                  <input type="text" name="codigo_postal" class="form-control" id="codigopostal-empresa" placeholder="Codigo Postal" value="{{empresa.codigo_postal}}">
      
                  <label for="ciudad-empresa">Ciudad</label>
                  <input type="text" name="ciudad" class="form-control" id="ciudad-empresa" placeholder="Ciudad" value="{{empresa.ciudad}}">
      
                  <label for="estado-empresa">Estado</label>
                  <input type="text" name="estado" class="form-control" id="estado-empresa" placeholder="Estado" value="{{empresa.estado}}">
      
                  <label for="pais-empresa">País</label>
                  <input type="text" name="pais" class="form-control" id="pais-empresa" placeholder="País" value="{{empresa.pais}}">
                </div>
      
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
              <button type="submit" class="btn btn-success">Guardar</button>
            </div>
      
          </form>
      
          </div>
        </div>
      </div>

bolsa_trabajo/templates/empresa_detail.html
{% extends 'base.html' %}
{% load static from staticfiles %}

{% block subtitle %}
Bolsa de Trabajo
{% endblock %}

{% block styles %}
{% endblock %}

{% block content %}
<h1 class="text-center">{{empresa.nombre}}</h1>

{% if form.errors %}
<div class="alert alert-danger alert-dismissible fade show align-self-center" role="alert">
  <ul>

    {% for error in form.non_field_errors %}
    <strong>{{ error }}</strong>
    {% endfor %}

  </ul>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
{% endif %}
{% if messages %}
<div class="alert alert-warning alert-dismissible fade show align-self-center" role="alert">
   <ul>
       {% for message in messages %}
       <li>{{ message }}</li>
       {% endfor %}
   </ul>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
    </button>
</div>
{% endif %}

<div class="text-left">
    <ul class="list-unstyled">
        <li>Telefono: {{empresa.telefono}}</li>
        <li>Dirección: {{empresa.calle}} #{{empresa.numero}},  Col.{{empresa.colonia}} {{empresa.codigo_postal}}. {{empresa.ciudad}},{{empresa.estado}},{{empresa.pais}}</li>
    </ul>
</div>

<div class="card">
    <div class="card-header">
        Contactos
    </div>
    <div class="card-body">
        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#add_contacto_empresa_modal"><i class="fas fa-plus-square"></i></button>
        <table class="table table-hover">
            <thead>
                <tr>
                    <th scope="col">Nombre</th>
                    <th scope="col">Telefono</th>
                    <th scope="col">Correo Electronico</th>
                    <th scope="col"></th>
                    
                </tr>
            </thead>
            <tbody>
                {% for contacto in contactos %}
                <tr>
                    
                    <td>{{ contacto.nombre }}</td>
                    <td>{{ contacto.telefono }}</td>  
                    <td>{{ contacto.email }}</td> 
                    <td>
                        <a class="btn btn-danger" href="{% url 'bolsa_trabajo:contacto-delete' contacto.id %}" role="button"><i class="fas fa-minus-square"></i></a>

                    </td> 
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="card-footer">
            <button type="button" class="btn btn-secondary" data-toggle="modal" data-target="#edit_empresa_modal">
                    Editar Información
            </button>
            <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#delete_empresa_modal">
                    Eliminar Empresa
            </button>
    </div>
</div>


{% include 'add_contacto_empresa_modal.html' %}
{% include 'delete_empresa_modal.html' %}
{% include 'edit_empresa_modal.html' %}


{% endblock %}


{% block scripts %}


{% endblock %}