accounts/urls.py
from django.urls import path, include
from . import views
from django.contrib.auth.models import User

app_name = 'accounts'

urlpatterns = [
    path('<str:matricula>', views.account, name="account"),
    path('login/', views.login_view, name="login"),
    path('signup/', views.signup_view, name="signup"),
    path('logout/', views.logout_view, name="logout"),
    path('update/', views.account_update, name="account_update")

]

bolsa_trabajo/urls.py
from django.urls import path

from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from bolsa_trabajo import views

app_name='bolsa_trabajo'

urlpatterns = [
    path('', views.bt_main, name="bt-home"),
    path('empresa_add/', views.empresa_add, name="empresa-add"),
    path('<str:id>/empresa_delete', views.empresa_delete, name="empresa-delete"),
    path('<str:id>/empresa_edit', views.empresa_edit, name="empresa-edit"),
    path('<str:id>', views.empresa_detail, name="empresa-detail"),
    path('<str:id>/contacto_add', views.empresa_contacto_add, name="contacto-add"),
    path('contacto_delete/<str:id>/', views.empresa_contacto_delete, name="contacto-delete")

]




urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

encuesta/urls.py
from django.urls import path
from encuesta import views
from django.contrib.auth.models import User

app_name = 'encuesta'

urlpatterns = [
    path('', views.encuesta_main, name="encuesta-home"),

]

exaven/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

app_name='exaven'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.homepage, name="home"),
    path('edu_continua/', views.edu_continua, name="edu-continua"),
    path('titulacion/', views.titulacion, name="titulacion"),
    path('accounts/', include('accounts.urls')),
    path('bolsa_trabajo/', include('bolsa_trabajo.urls', namespace='bolsa_trabajo')),
    path('encuesta/', include('encuesta.urls'))
]




urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static from staticfiles %}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>{% block subtitle %} {% endblock %} - {{ project_name }}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <!--<link rel="stylesheet" href="{% static '/bootstrap/css/bootstrap.min.css' %}">--->
    <link rel="stylesheet" href="{% static '/styles/styles.css' %}">
    <link rel="stylesheet" href="{% static '/plugins/fontawesome/css/all.min.css' %}">
    <style>
        #content-body{
          padding-top: 40px;
        }
    </style>
    {% block styles %}
  
    {% endblock %}
</head>
<body>
        <!-- Navigation -->
        <nav class="navbar navbar-expand navbar-dark bg-success">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample08" aria-controls="navbarsExample08" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
      
            <div class="collapse navbar-collapse justify-content-md-center" id="navbarsExample08">
              
                <span class="navbar-brand" href="#"><h1>Exaven</h1></span>
                <img src="http://ith.mx/logo_ith.jpg" alt="Logo_ith" width="50px" class="">
            </div>
          </nav>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark static-top ">
            <div class="container">
              
              <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse justify-content-md-center" id="navbarResponsive">
                <ul class="navbar-nav">
                  <li class="nav-item active">
                    <a class="nav-link" href="{% url 'home' %}">Inicio
                      <span class="sr-only">(current)</span>
                    </a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'bolsa_trabajo:bt-home' %}">Bolsa de Trabajo</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'edu-continua' %}">Educacion Continua</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="http://sistematitulacion.ith.mx:9494/Titulacion/">Titulación</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'encuesta:encuesta-home' %}">Encuesta de Egresados</a>
                  </li>
                  
                  {% if user.is_authenticated %}
                  <li class="nav-item">
                    <form class="logout-link" action="{% url 'accounts:logout' %}" method="POST">
                      {% csrf_token %}
                      <div class="dropdown">
                        <a id="username-display" class="btn btn-primary dropdown-toggle" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Bienvenido, {{ request.user.nombre }}</a>
                        <div class="dropdown-menu">
                            <a class="dropdown-item" href="{% url 'accounts:account' user.matricula %}">Mi Perfil</a>
                            <div class="dropdown-divider"></div>
                            <button type="submit" class="dropdown-item">Cerrar Sesión</button>
                        </div>
                      </div>
                    </form>
                  </li>
                  {% else %}
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:login' %}">Iniciar Sesión</a>
                  </li>
                  <li class="nav-item">
                      <a class="nav-link" href="{% url 'accounts:signup' %}">Registro</a>
                  </li>
                  {% endif %}
                </ul>
              </div>
            </div>
          </nav>
      
          <!-- Page Content -->
          <div class="container-fluid" id="content-body">
            {% block content %}

            {% endblock %}
          </div>

          <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
          <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
          <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
          <script src="{% static '/plugins/fontawesome/js/all.min.js' %}"></script>
          <script src="{% static '/scripts/scripts.js' %}"></script>
    <!--<script src="{% static '/bootstrap/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static '/bootstrap/popper.min.js' %}"></script>-->

    {% block scripts %}

    {% endblock %}
</body>
</html>